/*
 * LicensePanel.java
 *
 * Created on 17. November 2009, 12:21
 */

package marytts.tools.install;

import java.io.IOException;
import java.net.URL;
import java.util.SortedSet;

/**
 *
 * @author  marc
 */
public class LicensePanel extends javax.swing.JPanel {
    
    /** Creates new form LicensePanel */
    public LicensePanel(URL licenseURL, SortedSet<ComponentDescription> comps) {
        initComponents();
        StringBuilder sb = new StringBuilder();
        boolean isSingle = (comps.size() == 1);
        sb.append("The component");
        if (isSingle) {
            sb.append("s");
        }
        sb.append(":\n");
        boolean isFirst = true;
        for (ComponentDescription cd : comps) {
            if (!isFirst) {
                sb.append(", ");
            }
            sb.append(cd.getName());
            isFirst = false;
        }
        sb.append("\n");
        sb.append(isSingle ? "is" : "are");
        sb.append(" governed by the following license.");
        questionText.setText(sb.toString());
        
        try {
            licenseTextPane.setPage(licenseURL);
        } catch (IOException ioe) {
            licenseTextPane.setText("Unknown license -- only proceed if you are certain you have the right to install these components!");
            ioe.printStackTrace();
        }
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        questionText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        licenseTextPane = new javax.swing.JTextPane();

        jScrollPane1.setViewportView(licenseTextPane);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, questionText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(questionText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane licenseTextPane;
    private javax.swing.JLabel questionText;
    // End of variables declaration//GEN-END:variables
    
}
