/*
 * ProxyPanel.java
 *
 * Created on 22. September 2009, 18:48
 */

package marytts.tools.install;

/**
 *
 * @author  marc
 */
public class PasswordPanel extends javax.swing.JPanel {
    
    /** Creates new form ProxyPanel */
    public PasswordPanel() {
        initComponents();
    }
    
    public String getUser()
    {
        return tfUser.getText();
    }
    
    public char[] getPassword()
    {
        return passwordField.getPassword();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lName = new javax.swing.JLabel();
        lName1 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Authentication required"));
        lName.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        lName.setText("User");

        lName1.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        lName1.setText("Password");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tfUser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .add(lName)
                    .add(lName1)
                    .add(passwordField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(lName)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tfUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(lName1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(passwordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lName1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
    
}
