/*
 * POSWordPanel.java
 *
 * Created on 13 August, 2008, 11:04 AM
 */

package marytts.tools.voiceimport.firstvoice;

/**
 *
 * @author  sathish
 */
public class POSWordPanel extends javax.swing.JPanel {
    
    private POSWords word;
    
    /**
     * Creates new form POSWordPanel
     */
    public POSWordPanel() {
        initComponents();
    }
    
    /**
     * Creates new form POSWordPanel
     */
    public POSWordPanel(POSWords word) {
        this.word = word;
        initComponents();
        addWord();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        jLabel1.setText("Word");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Function");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                functionSelected(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Content");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentSelected(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(60, 60, 60)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 116, Short.MAX_VALUE)
                .add(jRadioButton1)
                .add(16, 16, 16)
                .add(jRadioButton2)
                .add(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jRadioButton1)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void contentSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentSelected
// TODO add your handling code here:
        //System.err.println("Content Selected");
        word.setType("content");
        word.setInspection(true);
    }//GEN-LAST:event_contentSelected

    private void functionSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_functionSelected
// TODO add your handling code here:
        //System.err.println("Function Selected");
        word.setType("function");
        word.setInspection(true);    
    }//GEN-LAST:event_functionSelected
    
    public POSWords getWord(){
        return this.word;
    }
    
    private void addWord(){
        //System.err.println(word.getWord());
        jLabel1.setText(word.getWord());
        if(word.getType().equals("function")){
            jRadioButton1.setSelected(true);
            jRadioButton2.setSelected(false);
        }
        else{
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(true);
        }
        this.updateUI();
        this.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
    
}
