#!/bin/bash
##########################################################################
# MARY TTS server
##########################################################################

# Set the Mary base installation directory in an environment variable:
export MARY_BASE="`dirname "$0"`"


java -showversion -Xms40m -Xmx1g -cp "$MARY_BASE/libs/*" -Dmary.base="$MARY_BASE" $* marytts.server.Mary
