#!/bin/csh -f

set SYLLA = ""
if ( "$1" == "-s" || "$2" == "-s" ) then
 set SYLLA = "-s"
endif

$LIA_PHON_REP/bin/lia_retik -r $LIA_PHON_REP/data/regles_retik | \
$LIA_PHON_REP/bin/lia_liaison $LIA_PHON_REP/data/regles_l.pro3 $LIA_PHON_REP/data/h_aspi.sirlex | \
$LIA_PHON_REP/bin/lia_phonetise -l -r $LIA_PHON_REP/data/french01.pron $SYLLA | \
$LIA_PHON_REP/bin/lia_pprocess -r $LIA_PHON_REP/data/rule_phon.pro $SYLLA | \
$LIA_PHON_REP/bin/lia_nett_phon $1 $2 | \
$LIA_PHON_REP/bin/lia_patch

