#!/bin/csh -f

# Extrait les noms propres supposee d'un texte

# $1 = '-reacc' or nothing

if ( $#argv == 1 ) then
 if ( "$1" != "-reacc" ) then
  echo 'Error: '$1' is an unknown option ....'
  echo 'The only option accepted here is: -reacc'
  exit
 endif
endif

$LIA_PHON_REP/script/lia_nett | \
$LIA_PHON_REP/script/lia_taggreac $1 | \
$LIA_PHON_REP/bin/lia_extract_name

