#!/bin/csh -f
#
# Check if the installation of the package 'LIA_PHON'
# is correct or not


$LIA_PHON_REP/script/lia_text2phon -reacc < $LIA_PHON_REP/doc/test.txt >!  $LIA_PHON_REP/doc/test.tmp
set l = `diff $LIA_PHON_REP/doc/test.tmp $LIA_PHON_REP/doc/test.pho | wc -l`
if ( $l == 0 ) then
 echo OK
 echo 'Congratulation, LIA_PHON is correctly installed'
else
 echo 'Sorry, something is wrong in your installation, check the README file'
endif
rm $LIA_PHON_REP/doc/test.tmp

