#!/bin/csh -f
# Phonetise une phrase en generant des variantes


# dos to unix conversion (when necessary)
tr -d "\r" | \
$LIA_PHON_REP/script/lia_nett | \
$LIA_PHON_REP/script/lia_taggreac | \
$LIA_PHON_REP/bin/lia_retik -r $LIA_PHON_REP/data/regles_retik | \
$LIA_PHON_REP/bin/lia_liaison $LIA_PHON_REP/data/regles_liaison_variante_en_contexte.pro3 $LIA_PHON_REP/data/h_aspi.sirlex | \
$LIA_PHON_REP/bin/lia_phonetise -l -r $LIA_PHON_REP/data/french01_var.pron | \
$LIA_PHON_REP/bin/lia_pprocess -r $LIA_PHON_REP/data/rule_phon.pro | \
$LIA_PHON_REP/bin/lia_genevari -r $LIA_PHON_REP/data/rule_variante_lex.pro | \
$LIA_PHON_REP/bin/lia_expand_phon