#!/bin/csh -f

if ( $#argv != 1 ) then
 echo 'Syntax: lia_delete_lexicon <lexicon name>'
 exit
endif


if ( -e $LIA_PHON_REP/data/$1.acc.graf ) then
 rm $LIA_PHON_REP/data/$1.acc.*
endif

if ( -e $LIA_PHON_REP/data/$1.graf ) then
 rm $LIA_PHON_REP/data/$1.graf
 rm $LIA_PHON_REP/data/$1.pmc*
 rm $LIA_PHON_REP/data/$1.sirlex*
endif

if ( -e $LIA_PHON_REP/data/$1.tab ) then
 rm $LIA_PHON_REP/data/$1.tab
endif

