#!/bin/csh -f
# Lance la chaine de traitement complete d'un texte
# avec passage au format MBROLA (avec generation
# d'une prosodie minimale)

# $1 = '-reacc' or nothing

if ( $#argv == 1 ) then
 if ( "$1" != "-reacc" ) then
  echo 'Error: '$1' is an unknown option ....'
  echo 'The only option accepted here is: -reacc'
  exit
 endif
endif

$LIA_PHON_REP/script/lia_text2phon $1 | \
$LIA_PHON_REP/bin/lia_add_proso

