/*
 * InstallerGUI.java
 *
 * Created on 17. September 2009, 15:45
 */

package marytts.tools.installvoices;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author  marc
 */
public class InstallerGUI extends javax.swing.JFrame
{
    List<LanguageComponentDescription> languages;
    List<VoiceComponentDescription> voices;
    
    /** Creates new form InstallerGUI */
    public InstallerGUI(List<LanguageComponentDescription> initialLanguages, List<VoiceComponentDescription> initialVoices) {
        this.languages = new ArrayList<LanguageComponentDescription>(initialLanguages);
        this.voices = new ArrayList<VoiceComponentDescription>(initialVoices);
        initComponents();
        customInitComponents();
        updateLanguagesTable();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        spLanguages = new javax.swing.JScrollPane();
        pLanguages = new javax.swing.JPanel();
        tLanguages = new javax.swing.JTable();
        pDownload = new javax.swing.JPanel();
        tfComponentListURL = new javax.swing.JTextField();
        bUpdate = new javax.swing.JButton();
        pInstallButtons = new javax.swing.JPanel();
        bInstall = new javax.swing.JButton();
        bUninstall = new javax.swing.JButton();
        bUninstall1 = new javax.swing.JButton();
        spVoices = new javax.swing.JScrollPane();
        pVoices = new javax.swing.JPanel();
        tVoices = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MARY TTS Installer");
        spLanguages.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        tLanguages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tLanguages.setSelectionBackground(new java.awt.Color(51, 102, 255));
        tLanguages.setSelectionForeground(new java.awt.Color(0, 0, 0));

        org.jdesktop.layout.GroupLayout pLanguagesLayout = new org.jdesktop.layout.GroupLayout(pLanguages);
        pLanguages.setLayout(pLanguagesLayout);
        pLanguagesLayout.setHorizontalGroup(
            pLanguagesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tLanguages, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );
        pLanguagesLayout.setVerticalGroup(
            pLanguagesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tLanguages, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );
        spLanguages.setViewportView(pLanguages);

        pDownload.setBorder(javax.swing.BorderFactory.createTitledBorder("Download languages and voices from:"));
        tfComponentListURL.setText("http://mary.dfki.de/download/4.0/mary-components.xml");

        bUpdate.setText("Update");

        org.jdesktop.layout.GroupLayout pDownloadLayout = new org.jdesktop.layout.GroupLayout(pDownload);
        pDownload.setLayout(pDownloadLayout);
        pDownloadLayout.setHorizontalGroup(
            pDownloadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pDownloadLayout.createSequentialGroup()
                .add(tfComponentListURL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 540, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bUpdate)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDownloadLayout.setVerticalGroup(
            pDownloadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pDownloadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(tfComponentListURL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(bUpdate))
        );

        bInstall.setText("Install selected");

        bUninstall.setText("Uninstall selected");

        bUninstall1.setText("Quit");

        org.jdesktop.layout.GroupLayout pInstallButtonsLayout = new org.jdesktop.layout.GroupLayout(pInstallButtons);
        pInstallButtons.setLayout(pInstallButtonsLayout);
        pInstallButtonsLayout.setHorizontalGroup(
            pInstallButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pInstallButtonsLayout.createSequentialGroup()
                .add(144, 144, 144)
                .add(bInstall, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(16, 16, 16)
                .add(bUninstall)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bUninstall1)
                .add(291, 291, 291))
        );
        pInstallButtonsLayout.setVerticalGroup(
            pInstallButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pInstallButtonsLayout.createSequentialGroup()
                .add(pInstallButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bInstall)
                    .add(bUninstall)
                    .add(bUninstall1))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spVoices.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        tVoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Language", ""
            }
        ));
        tVoices.setSelectionBackground(new java.awt.Color(51, 102, 255));
        tVoices.setSelectionForeground(new java.awt.Color(0, 0, 0));

        org.jdesktop.layout.GroupLayout pVoicesLayout = new org.jdesktop.layout.GroupLayout(pVoices);
        pVoices.setLayout(pVoicesLayout);
        pVoicesLayout.setHorizontalGroup(
            pVoicesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tVoices, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );
        pVoicesLayout.setVerticalGroup(
            pVoicesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tVoices, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );
        spVoices.setViewportView(pVoices);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(spLanguages, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 340, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(spVoices, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 360, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, pInstallButtons, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(pDownload, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(pDownload, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(spLanguages)
                    .add(spVoices))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pInstallButtons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void customInitComponents()
    {
        DescriptionTableModel m = new DescriptionTableModel("Language");
        tLanguages.setModel(m);
        tLanguages.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tLanguages.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    LanguageComponentDescription desc = (LanguageComponentDescription) tLanguages.getModel().getValueAt(tLanguages.getSelectedRow(), 1);
                    updateVoicesTable(desc);
                }
            }
        });
        TableColumnModel cm = tLanguages.getColumnModel();
        cm.getColumn(0).setPreferredWidth(20);
        cm.getColumn(2).setPreferredWidth(60);
        tLanguages.getColumnModel().getColumn(2).setCellRenderer(new ButtonRenderer());
        tLanguages.getColumnModel().getColumn(2).setCellEditor(new ButtonEditor());
        
        m = new DescriptionTableModel("Voice");
        tVoices.setModel(m);
        tVoices.getColumnModel().getColumn(2).setCellRenderer(new ButtonRenderer());
        tVoices.getColumnModel().getColumn(2).setCellEditor(new ButtonEditor());
        
    }

    private void updateLanguagesTable()
    {
        TableModel model = tLanguages.getModel();
        assert model instanceof DescriptionTableModel;
        ((DescriptionTableModel)model).setData(languages);
    }
    
    private void updateVoicesTable(LanguageComponentDescription currentLanguage)
    {
        List<VoiceComponentDescription> lVoices = getVoicesForLanguage(currentLanguage);
        TableModel model = tVoices.getModel();
        assert model instanceof DescriptionTableModel;
        ((DescriptionTableModel)model).setData(lVoices);
        
    }
    
    
    private List<VoiceComponentDescription> getVoicesForLanguage(LanguageComponentDescription language)
    {
        List<VoiceComponentDescription> lVoices = new ArrayList<VoiceComponentDescription>();
        for (VoiceComponentDescription v : voices) {
            if (v.getDependsLanguage().equals(language.getName())) {
                lVoices.add(v);
            }
        }
        return lVoices;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    throws Exception
    {
        final InstallFileParser p = new InstallFileParser(new URL("file:/Users/marc/Desktop/mary-component-description.xml"));
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstallerGUI(p.getLanguageDescriptions(), p.getVoiceDescriptions()).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInstall;
    private javax.swing.JButton bUninstall;
    private javax.swing.JButton bUninstall1;
    private javax.swing.JButton bUpdate;
    private javax.swing.JPanel pDownload;
    private javax.swing.JPanel pInstallButtons;
    private javax.swing.JPanel pLanguages;
    private javax.swing.JPanel pVoices;
    private javax.swing.JScrollPane spLanguages;
    private javax.swing.JScrollPane spVoices;
    private javax.swing.JTable tLanguages;
    private javax.swing.JTable tVoices;
    private javax.swing.JTextField tfComponentListURL;
    // End of variables declaration//GEN-END:variables
    
    public static class DescriptionTableModel extends AbstractTableModel
    {
        private String contentColumnHeader;
        private ComponentDescription[] data;
        
        public DescriptionTableModel(String contentColumnHeader)
        {
            this.contentColumnHeader = contentColumnHeader;
        }
        
        public void setData(List<? extends ComponentDescription> newData)
        {
            ComponentDescription[] newDataArray = (ComponentDescription[]) newData.toArray(new ComponentDescription[0]);
            data = newDataArray;
            fireTableDataChanged();
        }

        public String getColumnName(int col)
        {
            if (col == 1) {
                return contentColumnHeader;
            }
            return "";
        }
        
        public Class getColumnClass(int col)
        {
            switch(col) {
            case 0: return Boolean.class;
            case 1: return String.class;
            case 2: return String.class;
            }
            return null;
        }

        public int getRowCount()
        {
            if (data != null) {
                return data.length; 
            }
            return 0;
        }
        public int getColumnCount()
        {
            return 3;
        }
        
        public Object getValueAt(int row, int col)
        {
            if (data == null || data.length <= row) return null;
            switch(col) {
            case 0: return new Boolean(data[row].isSelected());
            case 1: return data[row];
            case 2: return "Details";
            }
            return null;
        }
        
        public void setValueAt(Object val, int row, int col)
        {
            if (col != 0) return;
            assert val instanceof Boolean;
            boolean selected = ((Boolean)val).booleanValue();
            data[row].setSelected(selected);
        }
        
        public boolean isCellEditable(int row, int col)
        {
            if (col == 0 || col == 2) return true;
            return false;
        }
        
    }
    
    /*
    public static class ButtonRenderer implements TableCellRenderer
    {
        public ButtonRenderer()
        {
        }
        
        public Component getTableCellRendererComponent(JTable table,
                Object button, boolean isSelected, boolean hasFocus, int row,
                int column)
        {
            JButton b = (JButton) button;
            return b;
        }
        
    }
    */

    // From http://www.java2s.com/Code/Java/Swing-Components/ButtonTableExample.htm
    class ButtonRenderer extends JButton implements TableCellRenderer {

      public ButtonRenderer() {
        setOpaque(true);
      }

      public Component getTableCellRendererComponent(JTable table, Object value,
          boolean isSelected, boolean hasFocus, int row, int column) {
        if (isSelected) {
          setForeground(table.getSelectionForeground());
          setBackground(table.getSelectionBackground());
        } else {
          setForeground(table.getForeground());
          setBackground(UIManager.getColor("Button.background"));
        }
        setText((value == null) ? "" : value.toString());
        return this;
      }
    }

    // From http://www.java2s.com/Code/Java/Swing-Components/ButtonTableExample.htm
    class ButtonEditor extends DefaultCellEditor {
      protected JButton button;
      private String label;
      private boolean isPushed;
      private ComponentDescription componentDescription;
      

      public ButtonEditor() {
        super(new JCheckBox());
        button = new JButton();
        button.setOpaque(true);
        button.addActionListener(new ActionListener() {
          public void actionPerformed(ActionEvent e) {
            fireEditingStopped();
          }
        });
      }

      public Component getTableCellEditorComponent(JTable table, Object value,
          boolean isSelected, int row, int column) {
        if (isSelected) {
          button.setForeground(table.getSelectionForeground());
          button.setBackground(table.getSelectionBackground());
        } else {
          button.setForeground(table.getForeground());
          button.setBackground(table.getBackground());
        }
        label = (value == null) ? "" : value.toString();
        button.setText(label);
        isPushed = true;
        componentDescription = (ComponentDescription) table.getValueAt(row, 1);
        return button;
      }

      public Object getCellEditorValue() {
        if (isPushed) {
            System.out.println("Button pressed for component "+componentDescription.getName());
        }
        isPushed = false;
        return new String(label);
      }

      public boolean stopCellEditing() {
        isPushed = false;
        return super.stopCellEditing();
      }

      protected void fireEditingStopped() {
        super.fireEditingStopped();
      }
    }

}
