/*
 * LanguagePanel.java
 *
 * Created on 17. September 2009, 16:31
 */

package marytts.tools.installvoices;

import java.awt.event.ItemEvent;
import java.util.Locale;

/**
 *
 * @author  marc
 */
public class LanguagePanel extends javax.swing.JPanel
{
    private LanguageComponentDescription desc;
    
    /** Creates new form LanguagePanel */
    public LanguagePanel(LanguageComponentDescription desc) 
    {
        this.desc = desc;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel8 = new javax.swing.JLabel();
        lLocale = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        lVersion = new javax.swing.JLabel();
        lNameValue = new javax.swing.JLabel();
        lLocaleValue = new javax.swing.JLabel();
        lVersionValue = new javax.swing.JLabel();
        cbSelect = new javax.swing.JCheckBox();
        lSize = new javax.swing.JLabel();
        lSizeValue = new javax.swing.JLabel();
        spDescription = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        lStatus = new javax.swing.JLabel();
        lStatusValue = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel8.setText("Version:");

        setBorder(javax.swing.BorderFactory.createTitledBorder("Language "+desc.getLocale().getDisplayName(Locale.ENGLISH)));
        lLocale.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        lLocale.setText("Locale:");

        lName.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        lName.setText("Name:");

        lVersion.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        lVersion.setText("Version:");

        lNameValue.setText(desc.getName());

        lLocaleValue.setText(desc.getLocale().toString());

        lVersionValue.setText(desc.getVersion());

        cbSelect.setSelected(desc.isSelected());
        cbSelect.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cbSelect.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cbSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSelectItemStateChanged(evt);
            }
        });

        lSize.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        lSize.setText("Size:");

        lSizeValue.setText(desc.getDisplayPackageSize());

        taDescription.setColumns(20);
        taDescription.setEditable(false);
        taDescription.setFont(new java.awt.Font("Courier New", 0, 10));
        taDescription.setRows(5);
        taDescription.setText(desc.getDescription());
        spDescription.setViewportView(taDescription);

        lStatus.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        lStatus.setText("Status:");

        lStatusValue.setText(desc.getStatus());

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(cbSelect)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lName)
                        .add(8, 8, 8)
                        .add(lNameValue)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lLocale)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lLocaleValue)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 59, Short.MAX_VALUE)
                        .add(lVersion)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lVersionValue)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lSize)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lSizeValue)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(spDescription, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                        .add(20, 20, 20))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lStatus)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lStatusValue)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lSizeValue)
                    .add(lSize)
                    .add(cbSelect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lName)
                    .add(lNameValue)
                    .add(lLocale)
                    .add(lLocaleValue)
                    .add(lVersionValue)
                    .add(lVersion))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spDescription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lStatus)
                    .add(lStatusValue))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSelectItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            desc.setSelected(false);
        } else {
            desc.setSelected(true);
        }
        
    }//GEN-LAST:event_cbSelectItemStateChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbSelect;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lLocale;
    private javax.swing.JLabel lLocaleValue;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lNameValue;
    private javax.swing.JLabel lSize;
    private javax.swing.JLabel lSizeValue;
    private javax.swing.JLabel lStatus;
    private javax.swing.JLabel lStatusValue;
    private javax.swing.JLabel lVersion;
    private javax.swing.JLabel lVersionValue;
    private javax.swing.JScrollPane spDescription;
    private javax.swing.JTextArea taDescription;
    // End of variables declaration//GEN-END:variables
    
}
