name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java_version: [ 8, 11, 17, 21 ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java_version }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew build --warning-mode all
